<?php
$this->headScript()->prependFile($this->baseUrl() . '/scripts/repas/repas.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/repas.css');
?>

<h1>Historique paiements</h1>

<section id="repas">
        <table id="tableRepas">
            
            <thead>
                <tr>
                    <th> ID payement </th>
                    <th> Date de recharge du compte</th>
                    <th> Montant </th>
                    <th> Référence </th>
                </tr>
            </thead>
            
            <tbody>
            <?php if($this->historique != null) : ?>
                <?php foreach($this->historique as $historique): ?>
                <tr>
                    <td>
                        <?php echo $historique["HistoriqueId"]; ?>
                    </td>
                    <td><span><?php echo $historique["HistoriqueDateUS"]; ?></span>
                        <?php echo $historique["HistoriqueDate"]; ?>
                    </td>
                    <td>
                        <?php echo $historique["HistoriqueMontant"]; ?>€
                    </td>
                    <td>
                        <?php echo $historique["HistoriqueReference"]; ?>
                    </td>
                </tr>
                <?php endforeach;?>
            <?php endif;?>
            </tbody>
            
        </table>
</section>