<html>
<head>
</head>
<body>

<h1>Bienvenue sur TRAC Fibre</h1>

<p>L'administrateur vient de créer votre compte pour l'application. Voici vos identifiants : </p>
<ul>
    <li><b>Identifiant :</b> <?php echo $this->username; ?></li>
    <li><b>Mot de passe :</b> <?php echo $this->password; ?></li>
</ul>
<p>A bientôt sur l'application <?php echo $this->baseUrl(); ?>
<p>Cordialement,
<br>TRAC Fibre</p>
<p>Merci de ne pas répondre à  ce courriel émis par un automate.</p>
</body>
</html>