
	<html>
<head>
</head>
<body>

<h1>Votre nouveau mot de passe TRAC Fibre</h1>

<p>Comme demandé, voici votre nouveau mot de passe TRAC Fibre </p>
<ul>
    <li><b>Mot de passe :</b> <?php echo $this->password; ?></li>
</ul>
<p>A bientôt sur l'application <?php echo $this->baseUrl(); ?>
<p>Cordialement,
<br>TRAC Fibre</p>
<p>Merci de ne pas répondre à  ce courriel émis par un automate.</p>
</body>
</html> 