<html>
    <head>
    </head>
    <body>

        <h1>Bonjour,</h1>

        <p>Vous trouverez ci-join votre ticket pour le repas du <b><?php echo $this->date ?></b></p>
        <br>
        <p>A bientôt sur l'application <a href="http://speedself-utec.com/">Speed Self</a>
        <p>Cordialement,
        <br>L'équipe Speed Self</p>
        <p>Merci de ne pas répondre à ce courriel émis par un automate.</p>
    </body>
</html>