<?php
$this->headScript()->prependFile($this->baseUrl() . '/scripts/accueil/editweek.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/editweek.css');
?>

<h1>Modification du menu de la semaine</h1>

<div class="dropper">
    <div class="draggable">#1</div>
    <div class="draggable">#2</div>
</div>


<div class="dropper">
    <div class="draggable">#3</div>
    <div class="draggable">#4</div>
</div>