<?php
$this->headScript()->prependFile($this->baseUrl() . '/scripts/accueil/accueil.js');
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/accueil.css');
$auth = Zend_Auth::getInstance();
?>

<h1>Accueil</h1>

<table class="accueil">
    <thead>
        <tr class="day">
            <th></th>
            <?php $i=1;
            foreach ($this->date as $date) {
                echo '<th>'.$this->jours[$i].'<br>'.$date.'</th>';
                $i++;
            }?>
        </tr>
    </thead>
    <tbody>
        <?php // Affichage des entrées
        $spanE = count($this->entree);
        $nbEntree=1;
        foreach ($this->entree as $entree) {
            echo '<tr class="entree">';
            if($nbEntree==1){
                echo '<th rowspan="'.$spanE.'">Entrée</th>';
            }
            for($jour=1 ; $jour<=5 ; $jour++){
                if(!isset($entree[$jour])){
                    echo '<td></td>';
                }else{ 
                    echo '<td>'.$entree[$jour].'</td>';
                }
            }
            echo '</tr>';
            $nbEntree++;
        }
        ?>
        
        <?php // Affichage des plats
        $spanP = count($this->plat);
        $nbPlat=1;
        foreach ($this->plat as $plat) {
            echo '<tr class="plat">';
            if($nbPlat==1){
                echo '<th rowspan="'.$spanP.'">Plat</th>';
            }
            for($jour=1 ; $jour<=5 ; $jour++){
                if(!isset($plat[$jour])){
                    echo '<td></td>';
                }else{ 
                    echo '<td>'.$plat[$jour].'</td>';
                }
            }
            echo '</tr>';
            $nbPlat++;
        }
        ?>
        
        <?php // Affichage des desserts
        $spanD = count($this->dessert);
        $nbDessert=1;
        foreach ($this->dessert as $dessert) {
            echo '<tr class="dessert">';
            if($nbDessert==1){
                echo '<th rowspan="'.$spanD.'">Dessert</th>';
            }
            for($jour=1 ; $jour<=5 ; $jour++){
                if(!isset($dessert[$jour])){
                    echo '<td></td>';
                }else{ 
                    echo '<td>'.$dessert[$jour].'</td>';
                }
            }
            echo '</tr>';
            $nbDessert++;
        }
        
        
        if ($auth->hasIdentity()) {
            $access = $auth->getIdentity()->IdAccessF;
            if($access == 1){ ?>
            <tr>
                <td rowspan="2"></td>
                <?php for($i=1;$i<=5;$i++){ ?>
                <td>
                    <?php if($this->date[$i-1] > '20/03/2018' /*date('d/m/Y')*/){ ?>
                    <form id='editDayForm' method='post' action='<?php echo $this->url(array('controller' => 'accueil','action' => 'editdaymenu'), null, true);?>'>
                        <button class="custom saveButton">Modifier</button>
                        <input class="hidden" type="text" name="date" value="<?php echo $this->date[$i-1] ?>">
                        <input class="hidden" type="text" name="day" value="<?php echo $i ?>">
                    </form>
                    <?php } ?>
                </td>
                <?php } ?>
            </tr>
            <?php }else{ ?>
            <tr>
                <td></td>
                <?php for($i=1;$i<=5;$i++){ ?>
                <td>
                    <?php if($this->reservation[$i] == 0){ 
                        if($this->date[$i-1] > '20/03/2018' /*date('d/m/Y')*/){?>
                    <form id='reservationForm' method='post' action='<?php echo $this->url(array('controller' => 'accueil','action' => 'reservation'), null, true);?>'>
                        <input class='hidden' type='text' name='date' value='<?php echo $this->date[$i-1]; ?>'>
                        <input class='hidden' type='text' name='day' value='<?php echo $i; ?>'>
                        <button class='custom saveButton'>Reserver</button>
                    </form>
                    <?php } }else { ?>
                    
                    <a href="<?php echo $this->baseUrl()."/repas/gestionticket/ticket/".$this->reservation[$i][$this->date[$i-1]];?>"> <button class='enveloppe saveButton'>Ticket</button> </a>
                    <?php } ?>
                </td>
                <?php } ?>
            </tr>
            <?php }
        } ?>
        </tbody>
</table>

<div class="fleche previous">
    <center>
        <a href="<?php echo $this->url(array("controller"=>"accueil","action"=>"index"), null, true)?>">
            <img src="<?php echo $this->baseUrl()."/images/icon/previous.png";?>" />
            <span><h3>Semaine précédente</h3></span>
        </a>
    </center>
</div>
<div class="fleche next">
    <center>
        <a href="<?php echo $this->url(array("controller"=>"accueil","action"=>"index"), null, true)?>">
            <img src="<?php echo $this->baseUrl()."/images/icon/next.png";?>" />
            <span><h3>Semaine suivante</h3></span>
        </a>
    </center>
</div>