<?php
//$this->headScript()->prependFile($this->baseUrl() . '/scripts/stock/gestionStock.js');
//$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/gestionStock.css');
?>

<div class="header">

    <div class="titre">
       <h1> Reservation du repas du <?php echo $this->date; ?> </h1>
    </div>
    
</div>

<h3> Entrée </h3>
<?php
foreach ($this->entree as $entree) {
    echo '<input type="checkbox" name="'.$entree['StockName'].'" value="'.$entree['StockPrice'].'">'.$entree['StockName'].' ('.$entree['StockPrice'].'€)<br>';
} ?>

<h3> Plat </h3>
<?php 
foreach ($this->plat as $plat) {
    echo '<input type="checkbox" name="'.$plat['StockName'].'" value="'.$plat['StockPrice'].'">'.$plat['StockName'].' ('.$plat['StockPrice'].'€)<br>';
} ?>

<h3> Dessert </h3>
<?php 
foreach ($this->dessert as $dessert) {
    echo '<input type="checkbox" name="'.$dessert['StockName'].'" value="'.$dessert['StockPrice'].'">'.$dessert['StockName'].' ('.$dessert['StockPrice'].'€)<br>';
} ?>

<button> Valider </button>
