<?php
$this->headLink()->appendStylesheet($this->baseUrl() . '/styles/aide.css');
?>

<h1> Aide </h1>


<center>
    <div class="contact">
        <h3 class="dev"> Documentation d'aide </h3>
        <div id="aide">
            <a href="<?php echo $this->url(array("controller"=>"footer","action"=>"getdocument"), null, true)?>"> Documentation : Mode opératoire </a>
        </div>
        
        <h3 class="dev"> FAQ </h3>
        <div class="faq">
            <b> Comment recharger mon solde ? </b><br>
            <i> Vous pouvez cliquer sur votre solde, en haut à droite de cette page, pour acceder à la recharge.
                Depuis cette page la transaction s'effectue en carte bleu et votre solde est credité immediatement. </i>
            <br><br>
            
            <b> Où puis-je récuperer mon ticket ? </b><br>
            <i> Les tickets sont disponible dans l'onglet "Accueil" dans la colonne du jour de la reservation et dans l'onglet "Mes repas" qui liste tous vos tickets. 
                Les tickets sont imprimable et exportable au format PDF. </i>
            <br><br>
            
            <b> Comment annuler une reservation ? </b><br>
            <i> ... </i>
            <br><br>
        </div>
        
    </div>
</center>