
<h1> Contact </h1>

<h3 class="dev"> Liens pour contacter la maintenance </h3>
<div>
    
    <p id="contactmail"><b> Email :</b> <a href="mailto:contactspeedself@gmail.com?subject=Demande SpeedSelf"> contactspeedself@gmail.com </a> </p>
    <p id="contacttelephone"><b> Telephone :</b> 01 23 45 67 89 </p>
    
    <center><p>La réponse à votre question est peut être dans la<a target="_blank" href="<?php echo $this->url(array("controller"=>"footer","action"=>"aide"), null, true)?>"> FAQ </a>.</p></center>
    
</div>