
<h1> Contact </h1>

<h3 class="dev"> Liens pour contacter les développeurs </h3>
<div class="contact">
    
    <div id="contact">
        <p><b> Nom et prénom :</b> POUDEVIGNE Cyprien </p>
        <p><b> Email :</b> <a href="mailto:cyprien.poudevigne@orange.com?subject=Demande TRAC&cc=hakim.assous@orange.com">cyprien.poudevigne@orange.com</a> </p>
        <p><b> Telephone :</b> 01 46 79 50 83 </p>
    </div>

    <div id="contact">
        <p><b> Nom et prénom :</b> ASSOUS Hakim </p>
        <p><b> Email :</b> <a href="mailto:hakim.assous@orange.com?subject=Demande TRAC&cc=cyprien.poudevigne@orange.com">hakim.assous@orange.com</a> </p>
        <p><b> Telephone :</b> 01 46 79 02 80 </p>
    </div>
    
</div>