
<html>
    <head>
        <meta http-equiv='Content-Type' content='text/html; charset=UTF-8' />
        <style> td{text-align: center;} </style>
    </head>
    <body>
        <?php
        if($this->users != null) { ?>
            <table>
                <thead>
                    <tr height="45">
                            <th>Code alliance</th>
                            <th>Nom</th>
                            <th>Prénom</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    foreach ($this->users as $user) {
                            echo "<tr>
                        <td>". $user['id'] ."</td>
                        <td>". $user['lastName'] ."</td>
                        <td>". $user['firstName'] ."</td>";
                        
                    } ?>
                </tbody>
            </table>
        <?php
        }else {
            echo "<body><H1>Aucune donnée disponible</H1></body>";
        } ?>
    </body>
</html>